# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Glow - CI

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:
  build:
    name: ${{ matrix.os }}-jdk${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: ['21', '17', '11']

    steps:
      - uses: actions/checkout@v3
        with:
            path: wildfly-glow
      - uses: actions/checkout@v2
        with:
            repository: wildfly/wildfly-maven-plugin
            path: wildfly-maven-plugin
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          cache: 'maven'
          distribution: 'temurin'
      - name: Build and Test on ${{ matrix.java }}
        run: mvn clean install
        shell: bash
        working-directory: wildfly-glow
      - name: Run cli tests using bash
        if: ${{ matrix.java != '11' }}
        run: bash tests/run-cli-tests.sh
        shell: bash
        working-directory: wildfly-glow
      - name: Run JBang tests using bash
        if: ${{ matrix.java != '11' && matrix.os != 'windows-latest'}} 
        run: bash tests/run-jbang-tests.sh
        shell: bash
        working-directory: wildfly-glow
      - name: Retrieve WildFly Glow version
        run: |
          echo "WILDFLY_GLOW_VERSION=$(mvn -B help:evaluate -Dexpression=project.version -DforceStdout -q)" >> $GITHUB_ENV
        shell: bash
        working-directory: wildfly-glow
      - name: Build and Test WildFly Maven Plugin on ${{ matrix.java }}
        run: mvn clean install -Dversion.org.wildfly.glow=${{ env.WILDFLY_GLOW_VERSION }}
        shell: bash
        working-directory: wildfly-maven-plugin
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: | 
           !**/target/**
           **/surefire-reports/*.txt